//
// Created by gunteam on 13/02/2020.
//

#ifndef CORBEAU_NEONAKIS_TOULARHMINE_TRIMOULET_UDPADRESSECONVERTIONEXCEPTION_H
#define CORBEAU_NEONAKIS_TOULARHMINE_TRIMOULET_UDPADRESSECONVERTIONEXCEPTION_H

#include <iostream>

class udpAdresseConvertionException {

public:
    udpAdresseConvertionException();

};


#endif //CORBEAU_NEONAKIS_TOULARHMINE_TRIMOULET_UDPADRESSECONVERTIONEXCEPTION_H
