//
// Created by gunteam on 13/02/2020.
//

#ifndef CORBEAU_NEONAKIS_TOULARHMINE_TRIMOULET_UDPRECEIVEEXCEPTION_H
#define CORBEAU_NEONAKIS_TOULARHMINE_TRIMOULET_UDPRECEIVEEXCEPTION_H

#include "iostream"

class udpReceiveException {

public:
    udpReceiveException();
};


#endif //CORBEAU_NEONAKIS_TOULARHMINE_TRIMOULET_UDPRECEIVEEXCEPTION_H
